stages:
- test
lint:
  stage: test
  image:
    name: registry.cern.ch/docker.io/library/python:3.10
  script:
  - pip install -U pip setuptools
  - pip install -r requirements_dev.txt
  - flake8 bin tests
test:
  stage: test
  image:
    name: registry.cern.ch/docker.io/library/python:3.10
  script:
  - apt-get -y update
  - apt-get -y install poppler-utils
  - pip install -U pip setuptools
  - pip install -r requirements_dev.txt
  - pytest tests

# Centrally supported security scanning
# See https://gitlab.docs.cern.ch/docs/Secure%20your%20application/sast
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
